global:
  controllerServiceAccount:
    namespace: arc-system
    name: bastet-cat-controller-stg-gha-rs-controller
  containerMode:
    type: dind
  environment: stg
  externalSecret:
    path: bastet-cat/arc-system
  extraAnnotations: {}
  extraLabels: {}
  flavours: {}
  githubConfigUrl: "https://github.com/bastet-cat"
  minRunners: 1
  maxRunners: 5
  org: bastet-cat
  template:
    # metadata:
    #   annotations:
    #     karpenter.sh/do-not-evict: "true"
    spec:
      # nodeSelector:
      #   provisioner: github-self-hosted
      #   karpenter.sh/capacity-type: on-demand
      # tolerations:
      #   - effect: NoSchedule
      #     key: github-self-hosted
      #     operator: Equal
      #     value: 'true'
  listenerTemplate:
    spec:
      containers:
      - name: listener
        securityContext:
          runAsUser: 1000
