apiVersion: v2
name: gha-runner-scale-set-stne
version: 1.0.0
description: A Helm chart for deploying my app
appVersion: 1.0.0
dependencies:
  - alias: runnerScaleSet
    name: gha-runner-scale-set
    version: 0.9.3
    repository: oci://ghcr.io/actions/actions-runner-controller-charts
