apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-apps-backend
spec:
  provider:
    vault:
      server: "{{ .Values.vault.server }}"
      path: "{{ .Values.vault.mountPath }}"
      version: "{{ .Values.vault.apiVersion }}"
      auth:
        tokenSecretRef:
          name: "{{ .Values.vault.secretName }}"
          namespace: "{{ .Release.Namespace }}"
          key: "{{ .Values.vault.secretProperty }}"
