global:

  # Controller Service Account
  controllerServiceAccount:
    namespace: arc-system
    name: bastet-cat-controller-stg-gha-rs-controller

  # AutoScalingRunnerSet container mode
  containerMode:
    type: dind

  # Environment composes RunnerScaleSet name
  environment: stg

  # External Secret definitions
  externalSecret:
    path: my-org/arc-system

  # Extra annotations to AutoScalingRunnerSet
  extraAnnotations: {}

  # Extra labels to AutoScalingRunnerSet
  extraLabels: {}

  # Flavours
  flavours:

    - name: small
      cpu: 1
      memory: 1Gi
      minRunners: 0

    - name: medium
      cpu: 3
      memory: 5Gi
      maxRunners: 2

  # Base url github repository
  githubConfigUrl: "https://github.com/my-org"

  # Default Min Runners (can be overrided by flavours)
  minRunners: 1

  # Default Max Runners (can be overrided by flavours)
  maxRunners: 5

  # Org name composes resources name
  org: my-org

  # Default runner template
  template:
    # metadata:
    #   annotations:
    #     karpenter.sh/do-not-evict: "true"
    spec:
      containers:
        - name: runner
          image: ghcr.io/actions/actions-runner:latest
          command: ["/home/runner/run.sh"]
          env:
            - name: DOCKER_HOST
              value: unix:///var/run/docker.sock
          volumeMounts:
            - name: work
              mountPath: /home/runner/_work
            - name: dind-sock
              mountPath: /var/run
    # nodeSelector:
    #   provisioner: github-self-hosted
    #   karpenter.sh/capacity-type: on-demand
    # tolerations:
    #   - effect: NoSchedule
    #     key: github-self-hosted
    #     operator: Equal
    #     value: 'true'
  # Default Listener template
  listenerTemplate:
    spec:
      containers:
      - name: listener
        securityContext:
          runAsUser: 1000
