global:
  controllerServiceAccount:
    namespace: arc-system
    name: bastet-cat-controller-stg-gha-rs-controller
  containerMode:
    type: dind
  environment: stg
  externalSecret:
    path: my-org/arc-system
  extraAnnotations: {}
  extraLabels: {}
  flavours:
    - name: small
      cpu: 1
      memory: 1Gi
      minRunners: 0
    - name: medium
      cpu: 3
      memory: 5Gi
      maxRunners: 2
  githubConfigUrl: "https://github.com/my-org"
  minRunners: 1
  maxRunners: 5
  org: my-org
  template:
    spec:
      containers:
        - name: runner
          image: ghcr.io/actions/actions-runner:latest
          command: ["/home/runner/run.sh"]
          env:
            - name: DOCKER_HOST
              value: unix:///var/run/docker.sock
          volumeMounts:
            - name: work
              mountPath: /home/runner/_work
            - name: dind-sock
              mountPath: /var/run
