x-anchors:
  runnerTemplate: &runnerTemplate
    spec:
      containers:
        - name: runner
          image: ghcr.io/actions/actions-runner:latest
          command: ["/home/runner/run.sh"]

global:
  flavours:
    - name: small-runner-stg
      cpu: 1
      memory: 1Gi
      minRunners: 1
      template:
        <<: *runnerTemplate
    # - name: medium-runner-stg
    #   cpu: 3
    #   memory: 7Gi
    #   template:
    #     <<: *runnerTemplate
    # - name: large-runner-stg
    #   cpu: 5
    #   memory: 7Gi
    #   template:
    #     <<: *runnerTemplate
    #     spec:
    #       containers:
    #       - name: runner
    #         image: ghcr.io/actions/actions-runner:2.319.1
    #         command: ["/home/runner/run.sh"]

