x-anchors:
  runnerTemplate: &runnerTemplate
    metadata:
      annotations:
        owner: "euclides.okamoto"
    spec:
      containers:
        - name: runner
          image: summerwind/actions-runner-dind:v2.318.0-ubuntu-20.04-a152741
          command: ["entrypoint-dind.sh"]
          env:
            - name: DOCKER_HOST
              value: unix:///var/run/docker.sock
          volumeMounts:
            - name: work
              mountPath: /home/runner/_work
            - name: dind-sock
              mountPath: /var/run


global:
  flavours:
    - name: small-runner-stg
      cpu: 1
      memory: 1Gi
      template:
        <<: *runnerTemplate
    - name: medium-runner-stg
      cpu: 3
      memory: 7Gi
      template:
        <<: *runnerTemplate
    - name: large-runner-stg
      cpu: 5
      memory: 32Gi
      template:
        <<: *runnerTemplate
        spec:
          containers:
          - name: runner
            image: ghcr.io/actions/actions-runner:2.319.1
            command: ["/home/runner/run.sh"]

