{{$:=list nil .}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ printf "%s-external-secret-%s" (include "gha-runners.resources-name-prefix" $) (include "gha-runners.resources-name-suffix" $) }}
spec:
  secretStoreRef:
    name: vault-apps-backend
    kind: ClusterSecretStore
  target:
    name: {{ include "gha-runners.githubsecret" $ }}
    creationPolicy: Owner
  data:
  - secretKey: "github_app_id"
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: "{{ .path }}"
      metadataPolicy: None
      property: "github-app-id"
  - secretKey: "github_app_installation_id"
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: "{{ .path }}"
      metadataPolicy: None
      property: "github-installation-id"
  - secretKey: "github_app_private_key"
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: "{{ .path }}"
      metadataPolicy: None
      property: "github-app-private-key"
