{{ $ := list nil .}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "gha-runners.managerRoleBindingName" $ }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gha-runners.labels" $ | nindent 4 }}
    app.kubernetes.io/component: manager-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "gha-runners.managerRoleName" $ }}
subjects:
- kind: ServiceAccount
  name: {{ include "gha-runners.managerServiceAccountName" $ | nindent 4 }}
  namespace: {{ include "gha-runners.managerServiceAccountNamespace" $ | nindent 4 }}
