apiVersion: apps/v1
kind: Deployment
metadata:
  name: smee-internals
spec:
  replicas: 3
  selector:
    matchLabels:
      app: smee-internals
  template:
    metadata:
      labels:
        app: smee-internals
    spec:
      containers:
      - name: my-container
          image: smee-internals:v0
