name: Publish Helm Chart

on:
  workflow_dispatch:
  push:
    paths:
      - 'assets/gha-runners/helm/**'
      - '.github/workflows/deploy-gha-runners-chart.yaml'

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    env:
      CHART_NAME: gha-runners

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Helm
      uses: azure/setup-helm@v4.2.0

    - name: Package and Publish Helm chart to GHCR
      run: |
        cd assets/${CHART_NAME}/helm
        echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io --username ${{ github.actor }} --password-stdin
        helm lint .
        helm package .
        version=$(helm show chart ./${CHART_NAME}-*.tgz | yq e '.version')
        ls ${CHART_NAME}-${version}.tgz
        target="oci://ghcr.io/${{ github.repository }}"
        echo -e "Publishing to \e[1m${target}\e[0m"
        helm push ${CHART_NAME}-${version}.tgz ${target}
      env:
        HELM_EXPERIMENTAL_OCI: 1
