name: Simple Tests for Self-Hosted Runners

on:
  workflow_dispatch:
  push:
    branches:
      - fix/reliable-cascading-values
    paths:
      - '.github/workflows/runner-test.yaml'

jobs:
  simple-test:
    runs-on: small-runner-stg
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Sleeping
        run: |
          echo "#${{ matrix.run }} - Sleeping for 5 seconds..."
          sleep 5
          echo "Waking up..."
